root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
extends:
  - eslint:recommended
  - prettier

rules:
  array-callback-return: error
  camelcase: off
  consistent-return: error
  eqeqeq: [error, smart]
  no-constant-condition: [error, checkLoops: false]
  no-implicit-globals: error
  no-unused-vars: [warn, argsIgnorePattern: '^_']
  prefer-const: [error, destructuring: all]

overrides:
  - files:
      - test/browser/tests/*.js
    env:
      mocha: true
  - files:
      - '*.{ts,tsx}'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
      '@typescript-eslint/no-unused-vars': [warn, argsIgnorePattern: '^_']
  - files:
      - '**/*.test.{ts,tsx}'
      - test/**/*.ts
    rules:
      '@typescript-eslint/ban-ts-comment': off
      '@typescript-eslint/no-explicit-any': off
  - files:
      - 'packages/mf2-compiler/**/*.{ts,tsx}'
      - 'packages/mf2-messageformat/**/*.{ts,tsx}'
    rules:
      '@typescript-eslint/ban-types':
        [error, { extendDefaults: true, types: { Function: false } }]
