root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2017
  sourceType: script
plugins:
  - prettier
extends:
  - "eslint:recommended"
  - prettier

rules:
  array-callback-return: error
  camelcase: error
  consistent-return: error
  eqeqeq: [error, smart]
  no-constant-condition: [error, checkLoops: false]
  no-implicit-globals: error
  prettier/prettier: error

overrides:
  - files:
      - rollup.config.js
      - packages/webpack-loader-example/src/*.js
      - test/src/*.js
    parserOptions:
      sourceType: module
