root: true
env:
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
  sourceType: script
plugins:
  - prettier
extends:
  - 'eslint:recommended'
  - plugin:prettier/recommended

rules:
  array-callback-return: error
  camelcase: error
  consistent-return: error
  eqeqeq: [error, smart]
  no-constant-condition: [error, checkLoops: false]
  no-implicit-globals: error
  prettier/prettier: error

overrides:
  - files:
      - rollup.config.js
      - packages/rollup-plugin/src/__fixtures__/*.js
      - packages/webpack-loader/example/src/*.js
      - test/browser/src/*.js
    parserOptions:
      sourceType: module
  - files:
      - test/browser/tests/*.js
    env:
      mocha: true
