root: true
env:
  commonjs: true
  es6: true
plugins:
  - prettier
extends:
  - 'eslint:recommended'
  - prettier

rules:
  array-callback-return: error
  camelcase: error
  consistent-return: error
  eqeqeq: [error, smart]
  no-constant-condition: [error, checkLoops: false]
  no-implicit-globals: error
  prettier/prettier: error

overrides:
  - files: [test/*.js]
    parserOptions: { ecmaVersion: 2017 }
    env:
      browser: true
      mocha: true
      node: true
    rules:
      no-unused-vars: 0

  - files: [test/browser/*.js]
    parserOptions: { ecmaVersion: 2017 }
    env:
      mocha: true
      node: true
    rules:
      camelcase: 0
      no-console: 0
