name: Node.js

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  node-16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 16.x }
      - run: npm ci
      - run: npm test
      - run: npm run build

  node-14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 14.x }
      - run: npm install --global npm@7
      - run: npm ci
      - run: npm test
      - run: npm run build

  node-12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 12.x }
      - run: npm install --global full-icu npm@7
      - run: echo "NODE_ICU_DATA=`node-full-icu-path 2>/dev/null`" >> $GITHUB_ENV
      - run: npm ci
      - run: npx jest --testPathIgnorePatterns examples/ packages/rollup-plugin/
      # https://github.com/actions/runner/issues/795
      - run: echo "NODE_ICU_DATA=" >> $GITHUB_ENV

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: 16.x }
      - run: npm ci
      - run: npm run lint
      - run: npx prettier --check .
